#library(remotes)
library(shiny)
library(shinydashboard)
library(leaflet)
library(leaflet.extras)
#library(DT)
library(lubridate)
library(sp)
library(dplyr)
library(tidyr)
library(jsonlite)
#library(stringi)
library(MonalisR)
library(MeteoBrowser)

initializeApp()
